---
- name: Install/Update pipx ansible
  become: true

  tasks:
  - name: Ensure pipx is at the latest version
    ansible.builtin.apt:
      name: pipx
      state: latest
      update_cache: yes
      cache_valid_time: 3600

  - name: pipxにPATHを通す
    ansible.builtin.command:
      cmd: pipx ensurepath
    register: execution_result

  - name: Install ansible with pipx
    ansible.builtin.command:
      cmd: pipx install --include-deps ansible
    register: execution_result
    
  - name: Install pywinrm with pipx
    ansible.builtin.command:
      cmd: pipx inject ansible pywinrm # if you installed ansible with pipx
    register: execution_result

  - name: コマンドの実行結果を確認
    ansible.builtin.debug:
      var: execution_result
  



